### ISSUE TITLE
It just hangs on my Macbook

### ISSUE THREAD

**Issue by ijt** [iogf/vy#25]
$ vy -v
# At this point it just sits there so I hit ctrl-C
^CTraceback (most recent call last):
  File "/usr/local/bin/vy", line 7, in <module>
    root.mainloop()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1125, in mainloop
    self.tk.mainloop(n)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1531, in __call__
    def __call__(self, *args):
KeyboardInterrupt

**Comment by iogf** [comment]
It seems something related with your installation of tkinter/python, try updating to 2.7.13.
Before updating check whether it is related with untwisted's reactor on mac.

Comment this line in your ~/.vy/vyrc file

    # Start untwisted reactor.
    import vyapp.plugins.startup

Check if it keeps hanging. Waiting for your reply.
